<?php
return [
['UTCoffset' => 'UTC +14',      'location' =>    "Christmas Island/Kiribati",                      'name' =>    "LINT",    'city' =>    "Kiritimati",      ],
['UTCoffset' => 'UTC +13:45',   'location' =>    "Chatham Islands/New Zealand",                    'name' =>    "CHADT",   'city' =>    "Chatham Islands", ],
['UTCoffset' => 'UTC +13',      'location' =>    "New Zealand with exceptions and 5 more",         'name' =>    "NZDT",    'city' =>    "Auckland",        ],
['UTCoffset' => 'UTC +12',      'location' =>    "Fiji, small region of Russia and 7 more",        'name' =>    "ANAT",    'city' =>    "Anadyr",          ],
['UTCoffset' => 'UTC +11',      'location' =>    "much of Australia and 6 more",                   'name' =>    "AEDT",    'city' =>    "Melbourne",       ],
['UTCoffset' => 'UTC +10:30',   'location' =>    "small region of Australia",                      'name' =>    "ACDT",    'city' =>    "Adelaide",        ],
['UTCoffset' => 'UTC +10',      'location' =>    "Queensland/Australia and 6 more",                'name' =>    "AEST",    'city' =>    "Brisbane",        ],
['UTCoffset' => 'UTC +9:30',    'location' =>    "Northern Territory/Australia",                   'name' =>    "ACST",    'city' =>    "Darwin",          ],
['UTCoffset' => 'UTC +9',       'location' =>    "Japan, South Korea and 5 more",                  'name' =>    "JST",     'city' =>    "Tokyo",           ],
['UTCoffset' => 'UTC +8:45',    'location' =>    "Western Australia/Australia",                    'name' =>    "ACWST",   'city' =>    "Eucla",           ],
['UTCoffset' => 'UTC +8',       'location' =>    "China, Philippines and 11 more",                 'name' =>    "CST",     'city' =>    "Beijing",         ],
['UTCoffset' => 'UTC +7',       'location' =>    "much of Indonesia, Thailand and 7 more",         'name' =>    "WIB",     'city' =>    "Jakarta",         ],
['UTCoffset' => 'UTC +6:30',    'location' =>    "Myanmar and Cocos Islands",                      'name' =>    "MMT",     'city' =>    "Yangon",          ],
['UTCoffset' => 'UTC +6',       'location' =>    "Bangladesh and 6 more",                          'name' =>    "BST",     'city' =>    "Dhaka",           ],
['UTCoffset' => 'UTC +5:45',    'location' =>    "Nepal",                                          'name' =>    "NPT",     'city' =>    "Kathmandu",       ],
['UTCoffset' => 'UTC +5:30',    'location' =>    "India and Sri Lanka",                            'name' =>    "IST",     'city' =>    "New Delhi",       ],
['UTCoffset' => 'UTC +5',       'location' =>    "Pakistan and 9 more",                            'name' =>    "UZT",     'city' =>    "Tashkent",        ],
['UTCoffset' => 'UTC +4:30',    'location' =>    "Afghanistan",                                    'name' =>    "AFT",     'city' =>    "Kabul",           ],
['UTCoffset' => 'UTC +4',       'location' =>    "Azerbaijan and 8 more",                          'name' =>    "GST",     'city' =>    "Dubai",           ],
['UTCoffset' => 'UTC +3:30',    'location' =>    "Iran",                                           'name' =>    "IRST",    'city' =>    "Tehran",          ],
['UTCoffset' => 'UTC +3',       'location' =>    "Moscow/Russia and 23 more",                      'name' =>    "MSK",     'city' =>    "Moscow",          ],
['UTCoffset' => 'UTC +2',       'location' =>    "Greece and 30 more",                             'name' =>    "EET",     'city' =>    "Cairo",           ],
['UTCoffset' => 'UTC +1',       'location' =>    "Germany and 45 more",                            'name' =>    "CET",     'city' =>    "Brussels",        ],
['UTCoffset' => 'UTC +0',       'location' =>    "United Kingdom and 24 more",                     'name' =>    "GMT",     'city' =>    "London",          ],
['UTCoffset' => 'UTC -1',       'location' =>    "Cabo Verde and 2 more",                          'name' =>    "CVT",     'city' =>    "Praia",           ],
['UTCoffset' => 'UTC -2',       'location' =>    "most of Greenland and 3 more",                   'name' =>    "CGT",     'city' =>    "Nuuk",            ],
['UTCoffset' => 'UTC -2:30',    'location' =>    "Newfoundland and Labrador/Canada",               'name' =>    "NDT",     'city' =>    "St. John's",      ],
['UTCoffset' => 'UTC -3',       'location' =>    "most of Brazil, Argentina and 10 more",          'name' =>    "ART",     'city' =>    "Buenos Aires",    ],
['UTCoffset' => 'UTC -4',       'location' =>    "regions of USA and 32 more",                     'name' =>    "EDT",     'city' =>    "New York",        ],
['UTCoffset' => 'UTC -5',       'location' =>    "regions of USA and 10 more",                     'name' =>    "CDT",     'city' =>    "Chicago",         ],
['UTCoffset' => 'UTC -6',       'location' =>    "small region of USA and 9 more",                 'name' =>    "CST",     'city' =>    "Mexico City",     ],
['UTCoffset' => 'UTC -7',       'location' =>    "regions of USA and 2 more",                      'name' =>    "PDT",     'city' =>    "Los Angeles",     ],
['UTCoffset' => 'UTC -8',       'location' =>    "Alaska/USA and 2 more",                          'name' =>    "AKDT",    'city' =>    "Anchorage",       ],
['UTCoffset' => 'UTC -9',       'location' =>    "Alaska/USA and regions of French Polynesia",     'name' =>    "HDT",     'city' =>    "Adak",            ],
['UTCoffset' => 'UTC -9:30',    'location' =>    "Marquesas Islands/French Polynesia",             'name' =>    "MART",    'city' =>    "Taiohae",         ],
['UTCoffset' => 'UTC -10',      'location' =>    "Hawaii/USA and 2 more",                          'name' =>    "HST",     'city' =>    "Honolulu",        ],
['UTCoffset' => 'UTC -11',      'location' =>    "American Samoa and 2 more",                      'name' =>    "NUT",     'city' =>    "Alofi",           ],
['UTCoffset' => 'UTC -12',      'location' =>    "much of US Minor Outlying Islands",              'name' =>    "AoE",     'city' =>    "Baker Island",    ],
];
